config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:edit, :update, :index]
  resources :groups, only: [:new, :edit, :create, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users, through: :user_groups
  has_many :messages

  validates :name, presence: true

  def last_msg
    if messages.blank?
      "まだメッセージはありません"
    else
      if messages.last.image?
        "画像が投稿されています"
      else
        messages.last.body
      end
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :body_or_image, presence: true

  def body_or_image
    body.presence or image.presence
  end

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :user_groups
  has_many :groups, through: :user_groups
  has_many :messages
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, unless: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_out_path_for(resource)
    user_session_path
  end

  def after_sign_in_path_for(resource)
    root_path
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
  end

  def new
    @group = Group.new
  end

  def edit
    set_group_params
  end

  def create
    @group = Group.create(create_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    set_group_params
    @group.update(create_params)
    redirect_to root_path, notice: 'グループを編集しました'
  end

  private
  def create_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group_params
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group, only: [:index, :create]

  def index
    @message = Message.new
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @message = Message.new(get_msg_params)
    if @message.save
      respond_to do |format|
        format.html {redirect_to group_messages_path, notice: 'メッセージを作成しました'}
        format.json
      end
    else
      flash[:alert] = 'メッセージを入力してください'
      render :index
    end
  end

  private
  def get_msg_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id, group_id: params[:group_id])
  end

  def set_group
    @group = Group.find(params[:group_id])
    @messages = @group.messages
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name like(?)', "%#{params[:keyword]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render action: :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_group.html.haml
= form_for @group, html: {class: 'new_chat_group', id: 'new_chat_group'} do |f|
  - if @group.errors.any?
    .chat-group-form__errors
      %h2
        #{@group.errors.count}件のエラーが発生しました。
        %ul
          - @group.errors.full_messages.each do |error_message|
            %li
              #{error_message}
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, 'グループ名', class: 'chat-group-form__label', for: 'chat_group_name'
    .chat-group-form__field--right
      = f.text_field :name, placeholder: 'グループ名を入力してください', class: 'chat-group-form__input', id: 'chat_group_name', value: group_name
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      =f.label :name, "チャットメンバーを追加", class: 'chat-group-form__label', for: "chat_group_チャットメンバーを追加"
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        = f.text_field :username, placeholder: "追加したいユーザー名を入力してください", class: 'chat-group-form__input', id: "user-search-field", value: ""
        #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, 'チャットメンバー', class: 'chat-group-form__label', for: 'chat_group_チャットメンバー'
    .chat-group-form__field--right
      #chat-group-users
        - if @group.users.length == 0
          .chat-group-user.clearfix
            = hidden_field_tag "group[user_ids][]", "#{current_user.id}"
            %p.chat-group-user__name
              #{current_user.name}
            %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除
        - else
          - @group.users.each do |user|
            .chat-group-user.clearfix
              = hidden_field_tag "group[user_ids][]", "#{current_user.id}"
              %p.chat-group-user__name
                #{user.name}
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "Save", class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: "group", locals: { group_name: @group.name}

app/views/groups/index.html.haml
= render partial: "layouts/sidebar"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: "group", locals: { group_name: ""}

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/_sidebar.html.haml
.sidebar
  .sidebar__user
    %p.sidebar__user__username
      = current_user.name
    = link_to "", edit_user_registration_path, class: "sidebar__user__btn-right fa fa-cog"
    = link_to "", new_group_path, class: "sidebar__user__btn-left fa fa-pencil-square-o"

  .sidebar__groups
    .sidebar__groups-list
      - current_user.groups.each do |group|
        .sidebar__group
          = link_to group_messages_path(group.id), class: "sidebar__group-content" do
            %p.sidebar__group-name #{group.name}
            %p.sidebar__group-messeage #{group.last_msg}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", 'http-equiv': "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_message_content.html.haml
.contents__body
  .contents__body__messeage-list
    - @messages.each do |message|
      .contents__body__messeage{data: {message_id: "#{message.id}"}}
        .contents__body__messeage-name #{message.user.name}
        .contents__body__messeage-time #{message.created_at.strftime('%Y-%m-%d %H:%M:%S')}
        .contents__body__messeage-body #{message.body}
        - if message.image?
          = image_tag message.image.thumb.url, class: "contents__body__messeage-image"

app/views/messages/index.html.haml
=   render partial: "layouts/sidebar"

.contents
  .contents__header
    .contents__header__infomation
      %p.contents__header__infomation-name #{@group.name}
      %p.contents__header__infomation-member-name
        MEMBER:
        - @group.users.each do |user|
          #{user.name}

    .contents__header__edit
      =link_to "edit", edit_group_path(@group.id), class: "contents__header__edit-btn"

  = render partial: 'message_content'

  .contents__footer
    .contents__footer__form
      = form_for [@group, @message], html: {class: 'contents__footer__form'} do |f|
        = f.text_field :body, placeholder: "type a message", id: "contents__footer__form"
        = f.label :image, class: "contents__footer__btn__input" do
          %i{"class":"fa fa-picture-o", "aria-hidden": "true"}
          = f.file_field :image, class: "contents__footer__btn__input-field"
        = f.button "Send",class: 'contents__footer__btn__send'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'